// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  introSidebar: [{type: 'autogenerated', dirName: 'intro'}],
  dappSidebar: [{type: 'autogenerated', dirName: 'dapp'}],
  validatorsSidebar: [{type: 'autogenerated', dirName: 'validators'}],
};

module.exports = sidebars;
