// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  learnSidebar: [{type: 'autogenerated', dirName: 'learn'}],
  buildSidebar: [{type: 'autogenerated', dirName: 'build'}],
  validatorsSidebar: [{type: 'autogenerated', dirName: 'validators'}],
  smpSidebar: [{type: 'autogenerated', dirName: 'smp'}],
  connectSidebar: [{type: 'autogenerated', dirName: 'connect'}],
};

module.exports = sidebars;
